name: Send email on push

on: [push]

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: New push to ${{ github.repository }}
          body: |
            A new push was made to ${{ github.repository }} by ${{ github.event.pusher.name }}.
            Commit message: ${{ github.event.head_commit.message }}
          to: juri.vaitmaa@gmail.com
          from: GitHub Actions
          content_type: text/plain
